version: '2'
services:
  a1:
    scale: 1
    health_check:
      interval: 10000
      initializing_timeout: 3000000
    upgrade_strategy:
      start_first: true
  a2:
    scale: 1
    health_check:
      port: 8080
      request_line: GET /health HTTP/1.0
      interval: 10000
      initializing_timeout: 300000
      unhealthy_threshold: 2
      healthy_threshold: 1
      strategy: none
      response_timeout: 6000
    upgrade_strategy:
      start_first: true
  a3:
    scale: 1
    health_check:
      port: 8080
      interval: 10000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      healthy_threshold: 1
      strategy: none
      response_timeout: 6000
    upgrade_strategy:
      start_first: true
  a4:
    scale: 1
    health_check:
      port: 8080
      interval: 10000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      healthy_threshold: 1
      strategy: none
      response_timeout: 6000
    upgrade_strategy:
      start_first: true
  rancher-cron:
    scale: 1
